config/routes.rb
Rails.application.routes.draw do
  get '/:locale' => 'blog#index'

  scope '(:locale)', locale: /en|id/ do
    root 'blog#index'

    get '/register', to: 'auth#register_form', as: 'register_form'
    post '/register', to: 'auth#register', as: 'register'

    get '/login', to: 'auth#login_form', as: 'login_form'
    post '/login', to: 'auth#login', as: 'login'
    get '/logout', to: 'auth#logout', as: 'logout'
    get '/settings', to: 'account#settings_form', as: 'settings_form'
    patch '/settings', to: 'account#settings', as: 'settings'

    get '/agreement', to: 'static#agreement', as: 'static_agreement'
    get '/privacy', to: 'static#privacy', as: 'static_privacy'

    get '/search', to: 'blog#search', as: 'blog_search'
    get '/article/:slug', to: 'blog#show', as: 'blog_show', slug: /[^\/]+/
    get '/category/:slug', to: 'blog#category', as: 'blog_category'
    get '/tag/:slug', to: 'blog#tag', as: 'blog_tag'
    get '/archive/:year/:month', to: 'blog#archive', as: 'blog_archive'
    get '/trending', to: 'blog#trending', as: 'blog_trending'

    get '/top_authors', to: 'author#top', as: 'top_authors'
    get '/author/:username', to: 'author#profile', as: 'profile', username: /[^\/]+/

    get '/contact', to: 'contact#form', as: 'contact'
    post '/contact/create', to: 'contact#create', as: 'contact_create'

    resources :articles do
      resources :comments
    end

    post '/articles/count', to: 'articles#counter', as: 'count_article'
    post '/comments/vote/:type', to: 'comments#vote', as: 'vote_comment'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }
  validates :email, presence: true
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    params = comment_params
    if is_authorized
      author = User.find(session.fetch(:authorized_id, '0'))
      params[:name] = author.name
      params[:email] = author.email
      params[:user_id] = author.id
    end

    if @article.comments.create(params)
      flash[:alert] = 'success'
      flash[:notice] = 'Your comment was successfully submitted.'
    else
      flash[:alert] = 'danger'
      flash[:notice] = 'Comment failed to submit, please try again.'
    end
    redirect_back(fallback_location: root_path, anchor: '#comment')
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.destroy
      flash[:alert] = 'warning'
      flash[:notice] = 'The comment was successfully deleted.'
    else
      flash[:alert] = 'danger'
      flash[:notice] = 'Comment failed to delete, please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def vote
    @comment = Comment.find(params[:id])
    if (params[:type] == 'up')
      @comment.votes = @comment.votes + 1
    else
      @comment.votes = @comment.votes - 1
    end
    if @comment.save
      render json: {
          status: 'success',
          code: 200,
          result: {
              id: @comment.id,
              views: @comment.votes
          }
      }
    else
      render json: {
          status: 'failed',
          code: 500,
          message: 'Internal server error'
      }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :email, :comment, :comment_id, :type)
  end
end

app/views/comments/_comment.html.erb
<%
  registeredCommenter = User.find_by_id(comment.user_id)
  if registeredCommenter.nil?
    avatar = 'noavatar.jpg'
  else
    avatar = registeredCommenter.avatar
  end
%>
<div class="media">
  <a class="d-flex pr-3" href="#">
    <img style="height: 64px; width: 64px; display: block; background: url('/images/avatars/<%= avatar %>') center center / cover">
  </a>
  <div class="media-body">
    <h5 class="mt-0">
      <% if(registeredCommenter.nil?) %>
          <%= comment.name %>
      <% else %>
          <%= link_to comment.name, profile_path(username: registeredCommenter.username) %>
      <% end %>
      <small class="text-muted small">(<%= comment.email %>)</small>
    </h5>
    <p class="text-muted small mb-1">
      <%= comment.created_at.strftime('%B %d, %Y %I:%M %p') %>
    </p>
    <%= comment.comment %>
    <ul class="list-inline comment-control" data-id="<%= comment.id %>">
      <li class="list-inline-item">
        <a href="<%= vote_comment_url type: 'up' %>" class="btn-vote" data-type="up">
          <span class="arrow arrow-up"></span>
        </a>
      </li>
      <li class="list-inline-item vote-counter">
        <%= comment.votes %>
      </li>
      <li class="list-inline-item">
        <a href="<%= vote_comment_url type: 'down' %>" class="btn-vote" data-type="down">
          <span class="arrow arrow-down"></span>
        </a>
      </li>
      <% unless counter == 0 %>
        <li class="list-inline-item">
          <%= link_to t(:action_reply), '#', class: 'btn-reply' %>
        </li>
      <% end %>
      <% if !registeredCommenter.nil? && is_authorized(registeredCommenter) || params[:controller] == 'articles' %>
        <li class="list-inline-item">
          <%= link_to t(:action_delete), [comment.article, comment], class: 'btn-delete-comment' %>
        </li>
      <% end %>

    </ul>

    <% if(comment.comments.count > 0) %>
        <%= render comment.comments, counter: counter-1 %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row mb-4" id="comment-form-wrapper">
  <div class="<%= params[:controller] == 'articles' ? 'col-lg-12' : 'col-lg-8' %>">

    <%= form_for([@article, @article.comments.build]) do |f| %>
        <input type="hidden" name="comment[comment_id]" value="">
        <% if is_authorized() %>
            <% author = User.find(session[:authorized_id]) %>
            <div class="d-block d-sm-flex text-center text-sm-left mb-1">
              <img class="mr-3 mb-1" style="width: 40px; height: 40px;"
                   src="/images/avatars/<%= author.avatar %>"
                   data-holder-rendered="true">
              <div>
                <h6 class="mb-1">
                  <a href="<%= url_for(controller: 'author', action: 'profile', username: author.username) %>" role="button">
                    <%= author.name %>
                  </a>
                </h6>
                <ul class="list-inline list-node text-muted mb-1">
                  <li class="list-inline-item">
                    <%= author.email %>
                  </li>
                  <li class="list-inline-item">
                    Total <%= t(:menu_articles) %> <%= author.articles.count %>
                  </li>
                </ul>
              </div>
            </div>
        <% else %>
            <div class="form-group">
              <%= f.label :name, t(:label_name) %>
              <%= f.text_field :name, class: 'form-control', placeholder: 'Your full name' %>
            </div>
            <div class="form-group">
              <%= f.label :email, t(:label_email) %>
              <%= f.email_field :email, class: 'form-control', placeholder: 'Email address' %>
            </div>
        <% end %>
        <div class="form-group">
          <%= f.label :comment, t(:label_comments) %>
          <%= f.text_area :comment, class: 'form-control', placeholder: 'Comment put here' %>
        </div>
        <div class="form-group">
          <%= submit_tag('Submit', {class: 'btn btn-primary'}) %>
        </div>
    <% end %>

  </div>
</div>


<div class="modal fade" id="modal-delete-comment">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="lead">Are you sure want to delete this comment?</p>
      </div>
      <div class="modal-footer">
        <form action="#" method="post">
          <input name="utf8" type="hidden" value="&#x2713;"/>
          <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
          <input name="_method" value="delete" type="hidden">
          <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>