config/routes.rb
Rails.application.routes.draw do
  get '/:locale' => 'blog#index'

  scope '(:locale)', locale: /en|id/ do
    root 'blog#index'

    get '/register', to: 'auth#register_form', as: 'register_form'
    post '/register', to: 'auth#register', as: 'register'

    get '/login', to: 'auth#login_form', as: 'login_form'
    post '/login', to: 'auth#login', as: 'login'
    get '/logout', to: 'auth#logout', as: 'logout'
    get '/settings', to: 'account#settings_form', as: 'settings_form'
    patch '/settings', to: 'account#settings', as: 'settings'

    get '/agreement', to: 'static#agreement', as: 'static_agreement'
    get '/privacy', to: 'static#privacy', as: 'static_privacy'

    get '/search', to: 'blog#search', as: 'blog_search'
    get '/article/:slug', to: 'blog#show', as: 'blog_show', slug: /[^\/]+/
    get '/category/:slug', to: 'blog#category', as: 'blog_category'
    get '/tag/:slug', to: 'blog#tag', as: 'blog_tag'
    get '/archive/:year/:month', to: 'blog#archive', as: 'blog_archive'
    get '/trending', to: 'blog#trending', as: 'blog_trending'

    get '/top_authors', to: 'author#top', as: 'top_authors'
    get '/author/:username', to: 'author#profile', as: 'profile', username: /[^\/]+/

    get '/contact', to: 'contact#form', as: 'contact'
    post '/contact/create', to: 'contact#create', as: 'contact_create'

    resources :articles do
      resources :comments
    end

    post '/articles/count', to: 'articles#counter', as: 'count_article'
    post '/comments/vote/:type', to: 'comments#vote', as: 'vote_comment'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  self.table_name = 'articles'
  self.primary_key = 'id'
  paginates_per 10

  enum status: {published: 'published', draft: 'draft'}

  validates :title, presence: true, length: { maximum: 200 }
  validates :slug, presence: true, length: { maximum: 500 }
  validates :content, presence: true, length: { minimum: 5, maximum: 10000 }
  validates :status, presence: true
  validates :category_id, presence: true
  validates :views, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user
  belongs_to :category, optional: true

  has_many :comments, dependent: :destroy
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  before_save :slugify

  def slugify
    if slug.present?
      self.slug = self.slug.strip.parameterize
    end
  end

  def to_param
    "#{id}-#{title.parameterize(preserve_case: true)}"
  end

  def all_tags=(tags)
    self.tags = tags.split(',').map do |tag_name|
      Tag.where(slug: tag_name.strip.parameterize, tag: tag_name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:tag).join(', ')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    if is_authorized
      article_data = @author.articles
      if params[:order_by] == 'popularity'
        article_data = article_data.order(views: :desc)
      else
        article_data = article_data.order(created_at: :desc)
      end
      @articles = article_data.page params[:page]
      @author = @author
    end
  end

  def show
    if is_authorized
      @article = Article.find(params[:id])
    end
  end

  def new
    if is_authorized
      @article = Article.new
    end
  end

  def create
    if is_authorized
      uploaded_io = params[:article][:featured]
      if !uploaded_io.nil?
        filename = Time.now.strftime('%Y-%m-%d_%H%M%S') + '_' + uploaded_io.original_filename
        File.open(Rails.root.join('public/images', 'features', filename), 'wb') do |file|
          file.write(uploaded_io.read)
          params[:article][:featured] = filename
        end
      else
        params[:article][:featured] = 'no-feature.jpg'
      end
      params[:article][:user_id] = @author.id

      @article = Article.new(article_params)

      if @article.save
        flash[:alert] = 'success'
        flash[:notice] = 'Article was successfully created.'
        redirect_to action: :index
      else
        flash.now[:alert] = 'danger'
        flash.now[:notice] = 'Something went wrong, try again or contact our support.'
        render 'new'
      end
    end
  end

  def edit
    if is_authorized
      @article = Article.find(params[:id])
    end
  end

  def update
    if is_authorized
      uploaded_io = params[:article][:featured]
      unless uploaded_io.nil?
        filename = Time.now.strftime('%Y-%m-%d_%H%M%S') + '_' + uploaded_io.original_filename
        File.open(Rails.root.join('public/images', 'features', filename), 'wb') do |file|
          file.write(uploaded_io.read)
          params[:article][:featured] = filename
        end
      end

      @article = Article.find(params[:id])
      @article.article_tags.destroy

      if @article.update(article_params)
        flash[:alert] = 'success'
        flash[:notice] = 'Article was successfully updated.'
        redirect_to action: :index
      else
        flash.now[:alert] = 'danger'
        flash.now[:notice] = 'Something went wrong, try again or contact our support.'
        render 'edit'
      end
    end
  end

  def destroy
    if is_authorized
      @article = Article.find(params[:id])

      if @article.destroy
        flash[:alert] = 'warning'
        flash[:notice] = 'Article was successfully deleted.'
      else
        flash[:alert] = 'danger'
        flash[:notice] = 'Something went wrong, try again or contact our support.'
      end

      redirect_to articles_path
    end
  end

  def counter
    @article = Article.find(params[:id])
    @article.views = @article.views + 1
    if @article.save
      render json: {
          status: 'success',
          code: 200,
          result: {
              id: @article.id,
              views: @article.views
          }
      }
    else
      render json: {
          status: 'failed',
          code: 500,
          message: 'Internal server error'
      }
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :slug, :content, :featured, :status, :user_id, :all_tags, :category_id)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_published_at(article)
    article.created_at.strftime('%B %d, %Y') if article && article.created_at.present?
  end

end

app/views/articles/_article.html.erb
<div class="mb-5">
  <img class="mb-3" style="height: 230px; width: 100%; display: block; background: url('/images/features/<%= article.featured %>') center center / cover">
  <h3>
    <a href="<%= url_for(controller: 'blog', action: 'show', slug: article.slug) %>">
      <%= article.title %>
    </a>
  </h3>
  <ul class="list-inline list-node">
    <li class="list-inline-item">
      <%= article.created_at.strftime('%B %d, %Y') %>
    </li>
    <li class="list-inline-item">
      <%= t(:label_by) %>
      <a href="<%= url_for(controller: 'author', action: 'profile', username: article.user.username) %>">
        <%= article.user.name %>
      </a>
    </li>
    <li class="list-inline-item">
      <%= article.comments.count %> <%= t(:label_comments) %>
    </li>
    <li class="list-inline-item">
      <%= article.views %> <%= t(:label_views) %>
    </li>
  </ul>
  <div class="mb-3">
    <%= truncate(strip_tags(article.content), length: 300, separator: ' ') %>
  </div>
  <a href="<%= url_for(controller: 'blog', action: 'show', slug: article.slug) %>" class="text-uppercase">
    <%= t(:label_read_more) %>
  </a>
</div>

app/views/articles/_article_card.html.erb
<div class="card mb-5">
  <img class="card-img-top" style="height: 180px; width: 100%; display: block; background: url('/images/features/<%= article.featured %>') center center / cover">
  <div class="card-body">
    <h4 class="card-title">
      <% if is_authorized(article) %>
          <a href="<%= article_path article %>">
            <%= article.title %>
          </a>
      <% else %>
          <a href="<%= url_for(controller: 'blog', action: 'show', slug: article.slug) %>">
            <%= article.title %>
          </a>
      <% end %>
    </h4>
    <ul class="list-inline list-node text-muted">
      <li class="list-inline-item">
        <%= t(:label_published_on) %> <%= article.created_at.strftime('%B %d, %Y') %>
      </li>
      <li class="list-inline-item">
        <%= t(:menu_categories) %>
        <a href="<%= url_for(controller: 'blog', action: 'category', slug: article.category.slug) %>">
          <%= article.category.category %>
        </a>
      </li>
      <li class="list-inline-item">
        <%= article.views %>x <%= t(:label_views) %>
      </li>
    </ul>

    <p class="card-text">
      <%= truncate(strip_tags(article.content), length: 300, separator: ' ') %>
    </p>
  </div>

  <% if is_authorized(article) %>
      <div class="card-footer">
        <div class="dropdown d-inline-block card-link">
          <a href="#" class="dropdown-toggle" type="button" data-toggle="dropdown">
            <i class="icon-share mr-1"></i> <%= t(:action_share) %>
          </a>
          <div class="dropdown-menu">
            <h6 class="dropdown-header"><%= t(:label_socials) %></h6>
            <a class="dropdown-item" target="_blank" href="https://facebook.com/sharer/sharer.php?u=<%= u(blog_show_url slug: article.slug) %>">
              <i class="icon-social-facebook mr-2"></i>Facebook
            </a>
            <a class="dropdown-item" target="_blank" href="https://twitter.com/intent/tweet/?text=<%= u('Great article!, ' + article.title + ' via @BlogStrap') %>">
              <i class="icon-social-twitter mr-2"></i>Twitter
            </a>
            <a class="dropdown-item" target="_blank" href="https://plus.google.com/share?url=<%= u(blog_show_url slug: article.slug) %>">
              <i class="icon-social-google mr-2"></i> Google
            </a>
            <a class="dropdown-item" target="_blank" href="mailto:?subject=<%= u('Great article!, ' + article.title) %>&body=<%= u('Hey ready this awesome article: ') + blog_show_url(slug: article.slug) %>">
              <i class="icon-envelope mr-2"></i> Email
            </a>
          </div>
        </div>
        <a href="<%= edit_article_path(article) %>" class="card-link">
          <i class="icon-note mr-1"></i> <%= t(:action_edit) %>
        </a>
        <a href="<%= article_path(article) %>" data-title="<%= article.title %>" class="card-link btn-delete-article">
          <i class="icon-trash mr-1"></i> <%= t(:action_delete) %>
        </a>
      </div>
  <% end %>
</div>

app/views/articles/_filter.html.erb
<div class="dropdown">
  <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <% if (params[:order_by] == 'popularity') %>
        <%= t(:sort_popularity) %>
    <% else %>
        <%= t(:sort_latest) %>
    <% end %>
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <h6 class="dropdown-header">Method</h6>
    <%
      if is_authorized(author) && params[:controller] == 'articles'
        sort_latest = articles_path order_by: 'latest'
        sort_popularity = articles_path order_by: 'popularity'
      else
        sort_latest = profile_path username: author.username, order_by: 'latest'
        sort_popularity = profile_path username: author.username, order_by: 'popularity'
      end
    %>
    <a class="dropdown-item" href="<%= sort_latest %>">
      <i class="icon-calendar mr-1"></i> <%= t(:sort_latest) %>
    </a>
    <a class="dropdown-item" href="<%= sort_popularity %>">
      <i class="icon-trophy mr-1"></i> <%= t(:sort_popularity) %>
    </a>
  </div>
</div>

app/views/articles/_form.html.erb
<% if flash[:alert] %>
    <div class="alert alert-<%= flash[:alert] %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= flash[:notice] %>
    </div>
<% end %>

<%= form_for @article, class: 'mb-5' do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, 'data-target': '#article_slug', class: "slugify form-control#{@article.errors[:title].any? ? ' is-invalid' : ''}", placeholder: 'Post title' %>
      <% if @article.errors[:name].any? %>
          <span class="form-text invalid-feedback"><%= @article.errors[:title][0] %></span>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :slug %>
      <div class="input-group">
        <span class="input-group-addon"><%= root_url %>/article/</span>
        <%= form.text_field :slug, class: "form-control#{@article.errors[:slug].any? ? ' is-invalid' : ''}", readonly: true %>
        <span class="input-group-btn">
          <button class="btn btn-primary" id="btn-edit-slug" data-target="#article_slug" type="button">Edit</button>
        </span>
      </div>
      <% if @article.errors[:slug].any? %>
          <span class="form-text invalid-feedback d-block"><%= @article.errors[:slug][0] %></span>
      <% else %>
          <small id="username-help" class="form-text text-muted">
            Automatic guessed, must be unique and separated by dash.
          </small>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :category_id, 'Category' %>
      <%= form.collection_select :category_id, Category.all, :id, :category, {prompt: 'Select a category'}, {class: "custom-select d-block form-control#{@article.errors[:category_id].any? ? ' is-invalid' : ''}"} %>
      <% if @article.errors[:category_id].any? %>
          <span class="form-text invalid-feedback"><%= @article.errors[:category_id][0] %></span>
      <% end %>
    </div>
    <div class="row">
      <div class="col col-sm-6">
        <div class="form-group">
          <%= form.label :status_published, 'Status' %>
          <div>
            <label class="custom-control custom-radio">
              <%= form.radio_button :status, 'published', {class: 'custom-control-input', checked: true} %>
              <span class="custom-control-indicator"></span>
              <span class="custom-control-description"> Published</span>
            </label>
            <label class="custom-control custom-radio">
              <%= form.radio_button :status, 'draft', {class: 'custom-control-input'} %>
              <span class="custom-control-indicator"></span>
              <span class="custom-control-description"> Draft</span>
            </label>
          </div>
          <% if @article.errors[:status].any? %>
              <span class="form-text invalid-feedback d-block"><%= @article.errors[:status][0] %></span>
          <% end %>
        </div>
      </div>
      <div class="col col-sm-6">
        <div class="form-group">
          <%= form.label :featured %>
          <div>
            <label class="custom-file">
              <%= form.file_field :featured, class: "custom-file-input#{@article.errors[:featured].any? ? ' is-invalid' : ''}" %>
              <span class="custom-file-control"></span>
            </label>
          </div>
          <% if @article.errors[:featured].any? %>
              <span class="form-text invalid-feedback"><%= @article.errors[:featured][0] %></span>
          <% end %>
        </div>
      </div>
    </div>
    <% unless @article.featured.blank? %>
        <div class="form-group">
          <img style="height: 180px; width: 100%; display: block; background: url('/images/features/<%= @article.featured %>') center center / cover">
        </div>
    <% end %>
    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class: "text-editor form-control#{@article.errors[:content].any? ? ' is-invalid' : ''}", placeholder: 'Article content', rows: 7 %>
      <% if @article.errors[:content].any? %>
          <span class="form-text invalid-feedback"><%= @article.errors[:content][0] %></span>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :all_tags, 'Tags' %>
      <div>
        <%= form.text_field :all_tags, class: "tags form-control#{@article.errors[:all_tags].any? ? ' is-invalid' : ''}", placeholder: 'Tags separated with comma' %>
      </div>
      <% if @article.errors[:all_tags].any? %>
          <span class="form-text invalid-feedback"><%= @article.errors[:all_tags][0] %></span>
      <% end %>
    </div>
    <div class="form-group mt-4">
      <%= submit_tag('Save Article', {class: 'btn btn-block btn-primary'}) %>
    </div>
<% end %>

app/views/articles/_viewer.html.erb
<ol class="breadcrumb pl-0 bg-transparent">
  <li class="breadcrumb-item">
    <a href="<%= root_path %>">
      <%= t(:menu_articles) %>
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%= blog_category_path slug: article.category.slug %>">
      <%= article.category.category %>
    </a>
  </li>
  <li class="breadcrumb-item active"><%= article.title %></li>
</ol>

<img class="mb-3" style="height: 230px; width: 100%; display: block; background: url('/images/features/<%= article.featured %>') center center / cover">

<h3><%= article.title %></h3>
<ul class="list-inline list-node">
  <li class="list-inline-item">
    <%= article.created_at.strftime('%B %d, %Y %I:%M %p') %>
  </li>
  <li class="list-inline-item">
    <%= t(:label_posted_by) %>
    <a href="<%= profile_path username: article.user.username %>">
      <%= article.user.name %>
    </a>
  </li>
  <li class="list-inline-item">
    <%= article.comments.count %> <%= t(:label_comments) %>
  </li>
  <li class="list-inline-item">
    <%= article.views %>x <%= t(:label_views) %>
  </li>
</ul>
<article>
  <%= raw article.content %>
</article>

<div class="lead mb-5">
  <% article.tags.each do |tag| %>
      <a href="<%= blog_tag_path slug: tag.slug %>" class="badge badge-pill badge-tag badge-primary">
        #<%= tag.tag %>
      </a>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        var viewerStorageKey = 'blogstrap-viewer';
        var voterStorageKey = 'blogstrap-voter';

        var localViewerData = localStorage.getItem(viewerStorageKey);
        var localVoterData = localStorage.getItem(voterStorageKey);

        var viewHistory = localViewerData == null ? [] : JSON.parse(localViewerData)
        var voteHistory = localVoterData == null ? [] : JSON.parse(localVoterData)

        function checkHistory(data, key) {
            var isExist = false;
            for (var i = 0; i < data.length; i++) {
                if (key == data[i]) {
                    isExist = true;
                    break;
                }
            }
            return isExist;
        }

        if (!checkHistory(viewHistory, <%= article.id %>)) {
            setTimeout(function () {
                $.ajax({
                    url: '<%= count_article_url %>',
                    method: 'post',
                    dataType: 'json',
                    data: {
                        id: '<%= article.id %>',
                        authenticity_token: window._token
                    },
                    success: function (data) {
                        viewHistory.push(data.result.id);
                        localStorage.setItem(viewerStorageKey, JSON.stringify(viewHistory));
                    },
                    error: function (data) {
                        console.log(data.message);
                        debugger;
                    }
                })
            }, 15000);
        }

        $('.btn-vote').on('click', function (e) {
            e.preventDefault();

            var parent = $(this).closest('ul');
            var commentId = parent.data('id');

            if (!checkHistory(voteHistory, commentId)) {
                parent.find('.btn-vote').addClass('disabled');

                var counterTag = parent.find('.vote-counter');
                var operatedWith = $(this).data('type') === 'up' ? 1 : -1;
                var operationResult = parseInt(counterTag.text()) + operatedWith;
                counterTag.html(operationResult).addClass(operationResult > 0 ? 'text-primary' : 'text-danger');

                $.ajax({
                    url: $(this).attr('href'),
                    method: 'post',
                    dataType: 'json',
                    data: {
                        id: commentId,
                        authenticity_token: window._token
                    },
                    success: function (data) {
                        voteHistory.push(data.result.id);
                        localStorage.setItem(voterStorageKey, JSON.stringify(voteHistory));
                    },
                    error: function (data) {
                        console.log(data.message);
                        debugger;
                    }
                });
            }
        })

        $('.comment-control').each(function () {
            var commentId = $(this).data('id');
            if (checkHistory(voteHistory, commentId)) {
                $(this).find('.btn-vote').addClass('disabled');
                var counterTag = $(this).find('.vote-counter');
                counterTag.addClass(parseInt(counterTag.text()) > 0 ? 'text-primary' : 'text-danger')
            }
        });
    });
</script>

app/views/articles/edit.html.erb
<% content_for :title do %> - Edit <%= @article.title %>
<% end %>

<%= render 'author/header' %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 ml-lg-auto mr-lg-auto">
      <div class="mb-5">
        <div class="mb-4">
          <h4>
            <a href="<%= articles_path %>">
              <i class="icon-arrow-left-circle mr-1 align-middle"></i>
            </a>
            Edit Post
          </h4>
          <p class="text-muted">Update old article</p>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% content_for :title do %> - <%= @author.name %>
<% end %>

<%= render 'author/header' %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 ml-lg-auto mr-lg-auto">
      <div class="row mb-4">
        <div class="col-6 mt-2">
          <h4><%= t(:menu_articles) %></h4>
        </div>
        <div class="col-6 text-right">
          <%= render partial: 'articles/filter', locals: {author: @author} %>
        </div>
      </div>

      <% if flash[:alert] %>
          <div class="alert alert-<%= flash[:alert] %>" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <% if @articles.count == 0 %>
          <p>No articles available yet, <a href="<%= new_article_path %>">create new</a> one</p>
          <% content_for :footer_fixed do %> fixed-bottom
          <% end %>
      <% end %>

      <%= render partial: 'articles/article_card', collection: @articles, as: :article, cached: true %>

      <%= paginate @articles %>

    </div>
  </div>
</div>

<div class="modal fade" id="modal-delete-article">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Article</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="lead">Are you sure want to delete this article
          <strong class="text-danger" id="article-title"></strong>?
        </p>
      </div>
      <div class="modal-footer">
        <form action="#" method="post">
          <input name="utf8" type="hidden" value="&#x2713;"/>
          <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
          <input name="_method" value="delete" type="hidden">
          <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<% content_for :title do %> - Create new post
<% end %>

<%= render 'author/header' %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 ml-lg-auto mr-lg-auto">
      <div class="mb-5">
        <div class="mb-4">
          <h4>
            <a href="<%= articles_path %>">
              <i class="icon-arrow-left-circle mr-1 align-middle"></i>
            </a>
            New Post
          </h4>
          <p class="text-muted">Publish new article</p>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% content_for :title do %> - <%= @article.title %>
<% end %>

<%= render 'author/header' %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 ml-lg-auto mr-lg-auto">

      <div class="mb-4 d-flex justify-content-between">
        <h4 class="d-flex align-items-center mb-0">
          <a href="<%= articles_path %>">
            <i class="icon-arrow-left-circle mr-2"></i>
          </a>
          Back to list
        </h4>
        <div>
          <a href="<%= edit_article_path @article %>" class="btn btn-primary">
            Edit Article <i class="icon-arrow-right-circle ml-1 align-middle"></i>
          </a>
          <a href="<%= blog_show_path slug: @article.slug %>" class="btn btn-primary">
            <i class="icon-eye align-middle"></i>
          </a>
        </div>
      </div>

      <% if flash[:alert] %>
          <div class="alert alert-<%= flash[:alert] %>" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <%= render partial: 'articles/viewer', locals: {article: @article} %>

      <h4 class="mb-4 mt-5"><%= t(:label_author) %></h4>
      <%= render partial: 'author/author_card', locals: {author: @article.user} %>

      <h4 class="mb-4 mt-5" id="comment"><%= t(:label_comments) %></h4>
      <%= render 'comments/form' %>

      <div class="mb-5 mt-5">
        <%= render @article.comments.where('comment_id IS NULL').order(created_at: :desc), counter: 2 %>
      </div>

    </div>
  </div>
</div>