config/routes.rb
Rails.application.routes.draw do
  get '/:locale' => 'blog#index'

  scope '(:locale)', locale: /en|id/ do
    root 'blog#index'

    get '/register', to: 'auth#register_form', as: 'register_form'
    post '/register', to: 'auth#register', as: 'register'

    get '/login', to: 'auth#login_form', as: 'login_form'
    post '/login', to: 'auth#login', as: 'login'
    get '/logout', to: 'auth#logout', as: 'logout'
    get '/settings', to: 'account#settings_form', as: 'settings_form'
    patch '/settings', to: 'account#settings', as: 'settings'

    get '/agreement', to: 'static#agreement', as: 'static_agreement'
    get '/privacy', to: 'static#privacy', as: 'static_privacy'

    get '/search', to: 'blog#search', as: 'blog_search'
    get '/article/:slug', to: 'blog#show', as: 'blog_show', slug: /[^\/]+/
    get '/category/:slug', to: 'blog#category', as: 'blog_category'
    get '/tag/:slug', to: 'blog#tag', as: 'blog_tag'
    get '/archive/:year/:month', to: 'blog#archive', as: 'blog_archive'
    get '/trending', to: 'blog#trending', as: 'blog_trending'

    get '/top_authors', to: 'author#top', as: 'top_authors'
    get '/author/:username', to: 'author#profile', as: 'profile', username: /[^\/]+/

    get '/contact', to: 'contact#form', as: 'contact'
    post '/contact/create', to: 'contact#create', as: 'contact_create'

    resources :articles do
      resources :comments
    end

    post '/articles/count', to: 'articles#counter', as: 'count_article'
    post '/comments/vote/:type', to: 'comments#vote', as: 'vote_comment'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  def profile
    @author = User.find_by_username!(params[:username])
    articleData = @author.articles
    if(params[:order_by] == 'popularity')
      articleData = articleData.order(views: :desc)
    else
      articleData = articleData.order(created_at: :desc)
    end
    @articles = articleData.page params[:page]
  end

  def top
    @authors = User.select('users.*, COUNT(articles.id) AS total_article')
                   .joins(:articles)
                   .group('users.id')
                   .order('total_article DESC')
                   .first(5)
    @onTheWeekAuthors = User.select('users.*, SUM(articles.views) AS total_view')
                            .joins(:articles)
                            .where('articles.created_at': (Time.now.midnight - 1.week)..Time.now.midnight)
                            .group('users.id')
                            .order('total_view DESC')
                            .first(8)
  end

end

app/views/author/_article.html.erb
<div class="card mb-4">
  <img class="card-img-top" style="height: 180px; width: 100%; display: block; background: url('/images/features/<%= article.featured %>') center center / cover">
  <div class="card-body">
    <h4 class="card-title">
      <a href="<%= url_for(controller: 'blog', action: 'show', slug: article.slug) %>">
        <%= article.title %>
      </a>
    </h4>
    <ul class="list-inline list-node text-muted">
      <li class="list-inline-item">
        <%= t(:label_published_on) %> <%= article.created_at.strftime('%B %d, %Y') %>
      </li>
      <li class="list-inline-item">
        <%= t(:menu_categories) %>
        <a href="<%= url_for(controller: 'blog', action: 'category', slug: article.category.slug) %>">
          <%= article.category.category %>
        </a>
      </li>
      <li class="list-inline-item">
        <%= article.views %>x <%= t(:label_views) %>
      </li>
    </ul>

    <p class="card-text">
      <%= truncate(strip_tags(article.content), length: 300, separator: ' ') %>
    </p>

    <% if !session[:is_authorized].nil? && article.user_id == session[:authorized_id]  %>
        <a href="#" class="card-link" data-toggle="modal" data-target="#dialog-share">
          <%= t(:action_share) %>
        </a>
        <a href="<%= edit_article_path(article) %>" class="card-link">
          <%= t(:action_edit) %>
        </a>
        <a href="<%= article_path(article) %>" data-title="<%= article.title %>" class="card-link btn-delete-article">
          <%= t(:action_delete) %>
        </a>
    <% end %>
  </div>
</div>

app/views/author/_author.html.erb
<div class="d-block d-sm-flex text-center text-sm-left mb-3">
  <a href="<%= url_for(controller: 'author', action: 'profile', username: author.username) %>">
    <img class="mr-sm-4 mb-3" style="width: 90px; height: 90px;"
       src="/images/avatars/<%= author.avatar %>"
       data-holder-rendered="true">
  </a>
  <div>
    <h5 class="mb-1">
      <a href="<%= url_for(controller: 'author', action: 'profile', username: author.username) %>" role="button">
        <%= author.name %>
      </a>
    </h5>
    <ul class="list-inline list-node text-muted mb-1">
      <li class="list-inline-item">
        Total <%= t(:menu_articles) %> <%= author.articles.count %>
      </li>
      <li class="list-inline-item d-sm-inline" hidden>
        <%= t(:label_since) %> <%= author.created_at.strftime('%B %d, %Y') %>
      </li>
    </ul>
    <p class="d-md-block">
      <%= author.about %>
    </p>
  </div>
  <hr class="d-sm-none">
</div>

app/views/author/_author_card.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-block d-sm-flex text-center text-sm-left">
      <img class="mr-sm-3 mb-3 mb-sm-0" style="width: 90px; height: 90px;"
           src="/images/avatars/<%= author.avatar %>"
           data-holder-rendered="true">
      <div>
        <p class="lead mb-3 mb-md-1">
          <strong><%= author.name %></strong>
          <small class="text-muted">@<%= author.username %></small>
        </p>
        <ul class="list-inline list-node text-muted mb-1">
          <li class="list-inline-item">
            Total <%= t(:menu_articles) %> <%= author.articles.count %>
          </li>
          <li class="list-inline-item d-sm-inline" hidden>
            <%= t(:label_since) %> <%= author.created_at.strftime('%B %d, %Y') %>
          </li>
        </ul>
        <p class="d-md-block
          <%= params[:controller] == 'articles' ? ' mb-0' : '' %>" hidden>
          <%= author.about %>
        </p>
        <% unless params[:controller] == 'articles' %>
            <a class="btn btn-primary" href="<%= url_for(controller: 'author', action: 'profile', username: author.username) %>" role="button">
              View Profile
            </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/author/_header.html.erb
<div class="jumbotron banner-overlay" style="background: url('/images/blog2.jpg') center center / cover">
  <div class="container banner-content">
    <div class="d-block d-sm-flex text-center text-sm-left">
      <img class="mr-sm-4 mb-3 mb-sm-0" style="width: 90px; height: 90px;"
           src="/images/avatars/<%= @author.avatar %>"
           data-holder-rendered="true">
      <div>
        <h3 class="mb-3 mb-md-1">
          <% if is_authorized(@author) %>
              <span class="d-md-inline" hidden>Welcome back, </span>
          <% end %>
          <strong><%= @author.name %></strong>
        </h3>
        <ul class="list-inline text-muted list-node mb-0">
          <li class="list-inline-item">
            Published <%= pluralize(@author.articles.count, 'article') %>
          </li>
          <li class="list-inline-item">
            Joined since <%= @author.created_at.strftime('%B %d, %Y') %>
          </li>
        </ul>
        <p class="d-md-block" hidden>
          <%= @author.about.nil? ? 'No story available' : @author.about %>
        </p>
        <% if is_authorized(@author) && params[:action] == 'index' %>
            <a class="btn btn-primary" href="<%= settings_form_path %>" role="button">
              <i class="icon-equalizer"></i>
            </a>
            <a class="btn btn-primary" href="<%= new_article_path %>" role="button">
              <i class="icon-note"></i> Create New Post
            </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/author/profile.html.erb
<% content_for :title do %> - <%= @author.name %>
<% end %>

<%= render 'author/header' %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 ml-lg-auto mr-lg-auto">
      <div class="row mb-4">
        <div class="col-6 mt-2">
          <h4><%= t(:menu_articles) %></h4>
        </div>
        <div class="col-6 text-right">
          <%= render partial: 'articles/filter', locals: {author: @author} %>
        </div>
      </div>

      <% if @articles.count == 0 %>
          <p>No articles available</p>
          <% content_for :footer_fixed do %> fixed-bottom
          <% end %>
      <% end %>

      <%= render partial: 'articles/article_card', collection: @articles, as: :article, cached: true %>

      <%= paginate @articles %>

    </div>
  </div>
</div>

app/views/author/top.html.erb
<% content_for :title do %> - Top Contributors
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-lg-8 ml-lg-auto mr-lg-auto">

      <div class="mb-4 mt-2">
        <h4><%= t(:label_contributors_on_the_week) %></h4>
      </div>

      <div class="mb-5">
        <% @onTheWeekAuthors.each do |author| %>
            <% cache author do %>
              <a title="<%= author.name %>" href="<%= url_for(controller: 'author', action: 'profile', username: author.username) %>">
                <img alt="<%= author.name %>" class="mr-3 mb-3" style="width: 70px; height: 70px;"
                     src="/images/avatars/<%= author.avatar %>"
                     data-holder-rendered="true">
              </a>
            <% end %>
        <% end %>

        <% if (@onTheWeekAuthors.empty?) %>
            <p>No author available</p>
        <% end %>
      </div>

      <div class="mb-4 mt-2">
        <h4><%= t(:menu_top_contributors) %></h4>
      </div>

      <%= render partial: 'author', collection: @authors, cached: true %>

    </div>
  </div>
</div>