config/routes.rb
Rails.application.routes.draw do
  get '/:locale' => 'blog#index'

  scope '(:locale)', locale: /en|id/ do
    root 'blog#index'

    get '/register', to: 'auth#register_form', as: 'register_form'
    post '/register', to: 'auth#register', as: 'register'

    get '/login', to: 'auth#login_form', as: 'login_form'
    post '/login', to: 'auth#login', as: 'login'
    get '/logout', to: 'auth#logout', as: 'logout'
    get '/settings', to: 'account#settings_form', as: 'settings_form'
    patch '/settings', to: 'account#settings', as: 'settings'

    get '/agreement', to: 'static#agreement', as: 'static_agreement'
    get '/privacy', to: 'static#privacy', as: 'static_privacy'

    get '/search', to: 'blog#search', as: 'blog_search'
    get '/article/:slug', to: 'blog#show', as: 'blog_show', slug: /[^\/]+/
    get '/category/:slug', to: 'blog#category', as: 'blog_category'
    get '/tag/:slug', to: 'blog#tag', as: 'blog_tag'
    get '/archive/:year/:month', to: 'blog#archive', as: 'blog_archive'
    get '/trending', to: 'blog#trending', as: 'blog_trending'

    get '/top_authors', to: 'author#top', as: 'top_authors'
    get '/author/:username', to: 'author#profile', as: 'profile', username: /[^\/]+/

    get '/contact', to: 'contact#form', as: 'contact'
    post '/contact/create', to: 'contact#create', as: 'contact_create'

    resources :articles do
      resources :comments
    end

    post '/articles/count', to: 'articles#counter', as: 'count_article'
    post '/comments/vote/:type', to: 'comments#vote', as: 'vote_comment'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>BlogStrap.io<%= yield :title %></title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= yield(:head) %>
</head>

<body class="pt-5">
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">BlogStrap.io</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= params[:controller] == 'blog' && params[:action] == 'index' ? 'active' : '' %>">
          <a class="nav-link" href="<%= root_url %>">
            <%= t(:menu_home) %>
          </a>
        </li>
        <li class="nav-item <%= params[:controller] == 'blog' && params[:action] == 'trending' ? 'active' : '' %>">
          <a class="nav-link" href="<%= url_for(controller: 'blog', action: 'trending') %>">
            <%= t(:menu_trending) %>
          </a>
        </li>
        <li class="nav-item <%= params[:controller] == 'author' && params[:action] == 'top' ? 'active' : '' %>">
          <a class="nav-link" href="<%= url_for(controller: 'author', action: 'top') %>">
            <%= t(:menu_top_contributors) %>
          </a>
        </li>
        <li class="nav-item dropdown <%= params[:action] == 'category' ? 'active' : '' %>">
          <a class="nav-link dropdown-toggle" href="#" id="navbarBrowse" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            <%= t(:menu_categories) %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarBrowse">
            <% @categoriesMenu.each do |category| %>
                <a class="dropdown-item <%= params[:action] == 'category' && params[:slug] == category.slug ? 'active' : '' %>"
                   href="<%= url_for(controller: 'blog', action: 'category', slug: category.slug) %>">
                  <%= category.category %>
                </a>
            <% end %>
          </div>
        </li>
      </ul>

      <% if is_authorized %>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
                 aria-expanded="false">
                <%= @loggedUser.name %>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <h6 class="dropdown-header">Main Menu</h6>
                <a class="dropdown-item <%= params[:controller] == 'articles' ? 'active' : '' %>" href="<%= articles_path %>">
                  <i class="icon-docs mr-2"></i> <%= t(:menu_articles) %>
                </a>
                <a class="dropdown-item <%= params[:controller] == 'account' ? 'active' : '' %>" href="<%= settings_path %>">
                  <i class="icon-equalizer mr-2"></i> <%= t(:menu_settings) %>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<%= logout_path %>">
                  <i class="icon-logout mr-2"></i> <%= t(:menu_sign_out) %>
                </a>
              </div>
            </li>
          </ul>
          <form class="form-inline ml-3">
            <a href="<%= new_article_path %>" class="btn btn-primary" type="button">
              <i class="icon-note"></i>
            </a>
          </form>
      <% else %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="<%= url_for(controller: 'auth', action: 'login') %>">
                Sign In
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= url_for(controller: 'auth', action: 'register') %>">
                Register
              </a>
            </li>
          </ul>
      <% end %>
    </div>
  </div>
</nav>

<%= yield %>

<div class="container<%= yield :footer_fixed %>">
  <hr>
  <footer class="row">
    <div class="col-md-6 text-center text-sm-left">
      <p>© BlogStrap.io 2017</p>
    </div>
    <div class="col-md-6 text-right d-sm-block" hidden>
      <ul class="list-inline">
        <% locales = %w(en id).map {|l| l.prepend '/'} %>
        <% baseUrl = request.protocol+request.host_with_port %>
        <% queryString = request.fullpath.sub(Regexp.union(locales), '') %>
        <li class="list-inline-item"><%= t(:label_language) %>:</li>
        <li class="list-inline-item"><%= link_to('English', "#{baseUrl}/en#{queryString}") %></li>
        <li class="list-inline-item mr-4"><%= link_to('Indonesia', "#{baseUrl}/id#{queryString}") %></li>

        <li class="list-inline-item">
          <a href="<%= url_for(controller: 'static', action: 'agreement') %>">
            <%= t(:menu_agreement) %>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="<%= url_for(controller: 'static', action: 'privacy') %>">
            <%= t(:menu_privacy) %>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="<%= url_for(controller: 'contact', action: 'form') %>">
            <%= t(:menu_contact_us) %>
          </a>
        </li>
      </ul>
    </div>
  </footer>
</div>

</body>
</html>

app/views/layouts/base.html.erb
<div class="jumbotron banner-overlay"<%= yield(:banner_image) %>>
  <div class="container banner-content">
    <%= content_for?(:banner_content) ? yield(:banner_content) : yield %>
  </div>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 col-lg-9">
      <div class="pr-xl-4">

        <%= render partial: 'articles/article', collection: @articles, cached: true %>

        <%= paginate @articles %>

      </div>
    </div>
    <div class="col-lg-3 d-md-block" hidden>
      <%= render 'sidebar' %>
    </div>
  </div>
</div>